### ISSUE TITLE
Add projects with import and search highlights of sermons

### ISSUE THREAD

**Issue by passionate2023** [meichthys/3D-Designs#1]
Hi,

Can you please add the list of software/project which allows sermons add i.e import of sermons in text file (.txt) and doc files (.doc/.docx) and have search with highlights in https://github.com/meichthys/christian-projects project?

As don't have an option to create issue in that project, created here.

Thanks

**Comment by meichthys** [comment]
I think you added this issue to the wrong repository. You probably wanted to add it here: https://github.com/meichthys/christian-projects

**Comment by passionate2023** [comment]
i am unable to add it there ? @meichthys how to add it there @meichthys

**Comment by meichthys** [comment]
Oh, i see. It's a fork of the original christian-projects repository so no issues are allows on forks by default. 
I've just enabled issues, so feel free to re-file it now 👍

**Comment by passionate2023** [comment]
done @meichthys . Thank you
